### ISSUE TITLE
Unable to compile on kernel-ml-5.7.11-1.el7.elrepo.x86_64.rpm

### ISSUE THREAD

**Issue by viready** [oskar456/xt_dns#7]
Hi

I'm trying to compile on linux CentOS 7 OS(**kernel-ml-5.7.11-1.el7.elrepo.x86_64.rpm**) 64 bit but getting the following errors:

Errors snippet
`In file included from ./include/linux/bug.h:5:0,
                 from ./include/linux/thread_info.h:12,
                 from ./arch/x86/include/asm/preempt.h:7,
                 from ./include/linux/preempt.h:78,
                 from ./include/linux/spinlock.h:51,
                 from ./include/linux/seqlock.h:36,
                 from ./include/linux/time.h:6,
                 from ./include/linux/stat.h:19,
                 from ./include/linux/module.h:13,
                 from /root/xt_dns-1.3/xt_dns.c:14:
./arch/x86/include/asm/bug.h:35:22: error: expected identifier or ‘(’ before string constant
  asm_inline volatile("1:\t" ins "\n"    \
                      ^
./arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
  ^
./include/asm-generic/bug.h:98:3: note: in expansion of macro ‘__WARN_FLAGS’
   __WARN_FLAGS(BUGFLAG_ONCE |   \
   ^
./include/linux/netfilter.h:334:3: note: in expansion of macro ‘WARN_ON_ONCE’
   WARN_ON_ONCE(1);
   ^
In file included from <command-line>:0:0:
././include/linux/compiler_types.h:201:24: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration                                                                                                                                                                                                                                                             -after-statement]
 #define asm_inline asm __inline
                        ^
./arch/x86/include/asm/bug.h:35:2: note: in expansion of macro ‘asm_inline’
  asm_inline volatile("1:\t" ins "\n"    \
  ^
./arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
  ^
./include/asm-generic/bug.h:98:3: note: in expansion of macro ‘__WARN_FLAGS’
   __WARN_FLAGS(BUGFLAG_ONCE |   \
   ^
./include/linux/netfilter.h:334:3: note: in expansion of macro ‘WARN_ON_ONCE’
   WARN_ON_ONCE(1);
   ^
make[3]: *** [/root/xt_dns-1.3/xt_dns.o] Error 1
make[2]: *** [/root/xt_dns-1.3] Error 2
make[1]: *** [sub-make] Error 2
make[1]: Leaving directory /usr/src/kernels/5.7.11-1.el7.elrepo.x86_64'
make: *** [xt_dns.ko] Error 2`


This software worked without any issues on **kernel-ml-5.4.4-1.el7.elrepo.x86_64**

`

**Comment by oskar456** [comment]
This is very likely caused by old version of C compiler incompatible with the build system of the kernel 5.7. I'm not sure there's anything I can do about that.
