### ISSUE TITLE
Unable to compile on 32 bit centos 5.10

### ISSUE THREAD

**Issue by viready** [oskar456/xt_dns#2]
Trying latest version.

> **[root@localhost xt_dns-1.3]# make**
> make -C /lib/modules/2.6.18-371.el5/build M=/tmp/xt_dns-1.3 modules
> make[1]: Entering directory /usr/src/kernels/2.6.18-371.4.1.el5-i686
> CC [M]  /tmp/xt_dns-1.3/xt_dns.o
> /tmp/xt_dns-1.3/xt_dns.c:81: warning: âstruct xt_match_paramâ declared inside parameter list
> /tmp/xt_dns-1.3/xt_dns.c:81: warning: its scope is only this definition or declaration, which is probably not what you want
> /tmp/xt_dns-1.3/xt_dns.c: In function âdns_mtâ:
> /tmp/xt_dns-1.3/xt_dns.c:86: error: dereferencing pointer to incomplete type
> /tmp/xt_dns-1.3/xt_dns.c:96: error: dereferencing pointer to incomplete type
> /tmp/xt_dns-1.3/xt_dns.c:101: error: dereferencing pointer to incomplete type
> /tmp/xt_dns-1.3/xt_dns.c: At top level:
> /tmp/xt_dns-1.3/xt_dns.c:223: warning: âstruct xt_mtchk_paramâ declared inside parameter list
> /tmp/xt_dns-1.3/xt_dns.c: In function âdns_mt_checkâ:
> /tmp/xt_dns-1.3/xt_dns.c:225: error: dereferencing pointer to incomplete type
> /tmp/xt_dns-1.3/xt_dns.c: At top level:
> /tmp/xt_dns-1.3/xt_dns.c:253: warning: âstruct xt_mtchk_paramâ declared inside parameter list
> /tmp/xt_dns-1.3/xt_dns.c: In function âdns_mt6_checkâ:
> /tmp/xt_dns-1.3/xt_dns.c:255: error: dereferencing pointer to incomplete type
> /tmp/xt_dns-1.3/xt_dns.c: At top level:
> /tmp/xt_dns-1.3/xt_dns.c:287: error: âNFPROTO_IPV4â undeclared here (not in a function)
> /tmp/xt_dns-1.3/xt_dns.c:288: warning: initialization from incompatible pointer type
> /tmp/xt_dns-1.3/xt_dns.c:289: warning: initialization from incompatible pointer type
> /tmp/xt_dns-1.3/xt_dns.c:296: error: âNFPROTO_IPV6â undeclared here (not in a function)
> /tmp/xt_dns-1.3/xt_dns.c:297: warning: initialization from incompatible pointer type
> /tmp/xt_dns-1.3/xt_dns.c:298: warning: initialization from incompatible pointer type
> /tmp/xt_dns-1.3/xt_dns.c: In function âdns_initâ:
> /tmp/xt_dns-1.3/xt_dns.c:307: error: implicit declaration of function âxt_register_matchesâ
> /tmp/xt_dns-1.3/xt_dns.c: In function âdns_exitâ:
> /tmp/xt_dns-1.3/xt_dns.c:313: error: implicit declaration of function âxt_unregister_matchesâ
> make[2]: **\* [/tmp/xt_dns-1.3/xt_dns.o] Error 1
> make[1]: **\* [_module_/tmp/xt_dns-1.3] Error 2
> make[1]: Leaving directory /usr/src/kernels/2.6.18-371.4.1.el5-i686
> make: **\* [xt_dns.ko] Error 2
> **[root@localhost xt_dns-1.3]# uname -a**
> Linux localhost.localdomain 2.6.18-371.el5  #1 SMP Tue Oct 1 08:37:57 EDT 2013 i686 i686 i386 GNU/Linux
> **[root@localhost xt_dns-1.3]# cat /etc/redhat-release**
> CentOS release 5.10 (Final)
> **[root@localhost xt_dns-1.3]# iptables --version**
> iptables v1.4.21

Thanks
